# Generated by Django 3.0 on 2019-12-27 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meet', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyweight', models.IntegerField()),
                ('letter', models.CharField(max_length=1)),
                ('start_time', models.TimeField()),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet.Meet')),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('date_of_birth', models.DateField()),
                ('gender', models.BooleanField()),
                ('bodyweight', models.FloatField()),
                ('affiliation', models.CharField(max_length=3)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.Session')),
            ],
        ),
    ]
