# Generated by Django 3.0 on 2019-12-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_lift'),
    ]

    operations = [
        migrations.AddField(
            model_name='lift',
            name='changes',
            field=models.IntegerField(default=0),
        ),
    ]
